# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
jobs:
  build:
    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: '8'
      - name: Compile with Maven
        run: mvn --show-version --batch-mode -DskipTests=true -Dgpg.skip=true --activate-profiles sonatype-oss-release install
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: '14'
      - name: Test with Maven
        run: mvn --show-version --batch-mode verify
name: test
on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [ '**' ]
